function [chiS_eff, chiN_eff, info] = effective_chi_macro(p, grid)
%EFFECTIVE_CHI_MACRO Effective drift amplitudes in the sign-response macro limit.
%
% For phi(y)=-sign(y), the macroscopic velocity generated by one signal is
% chi_eff*sign(q_x), where
%
%   chi_eff = chi * response_scale * int_V |v|dv / |V|.
%
% With p.normalize_phi_amplitude=true, chi_eff equals the user-specified chi.

scale = model.response_scale(grid, p);
abs_moment = utils.vint(abs(grid.v), grid.w);
factor = scale * abs_moment / grid.V;
chiS_eff = p.chiS * factor;
chiN_eff = p.chiN * factor;

info = struct();
info.phi_scale_total = scale;
info.abs_moment = abs_moment;
info.V = grid.V;
info.factor = factor;
info.chiS_input = p.chiS;
info.chiN_input = p.chiN;
info.chiS_eff = chiS_eff;
info.chiN_eff = chiN_eff;
end
