dir_name = 'data_kinetic';
if ~exist(dir_name,'dir')
    mkdir(dir_name);
end
cd(dir_name);
data_file = ...
    strcat('data_kinetic_ChiC_', num2str(mypara.chi_c), ...  
    '_ChiN_', num2str(mypara.chi_n), ... 
    '_eps_', num2str(mypara.eps, '%.0e'),...
    '_T_', num2str(round(T), '%i'),...
    '_dt_', num2str(dt, '%.0e'),...
    '_Nx_', num2str(domain.x_number), ...
    '.mat');
if kT == NT
    save(data_file, 'domain', 'mypara', 'myfunc', 'rho', ...
        'c', 'n', 'G', 'T');
else
   save(data_file, 'domain', 'mypara', 'myfunc', 'rho', ...
        'c', 'G', 'T');
end
cd ..